name: first_workflow

on: [workflow_dispatch,push] #Trigger when this workflow will be run 

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: first-step
      run: echo "Hello from dhruv"
    - name: second-step
      run: echo "Bye from dhruv"
    - name: listing the file
      run: ls