name: first_workflow
on: push
jobs:

  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checking out the code
      uses: actions/checkout@v6
    - name: executing the shell script
      run: | 
        chmod +x ./dhruv.sh
        sudo ./dhruv.sh
    - name: listing the code
      run: | 
          ls
          echo "hello from gihub action"
          cat ./a.txt
    
  second_job:
    needs:
      - first_job
    runs-on: ubuntu-latest
    steps:
    - name: I am second job
      run: ls