name: first_workflow
on: push
jobs:

  first_job:
    runs-on: ubuntu-latest
    
    steps:

    - name: checking out the code
      uses: actions/checkout@v6

    - name: listing the code
      run: ls